os: Visual Studio 2017

version: ci-{build}

init:
  - git config --global core.eol native
  - git config --global core.autocrlf true

clone_depth: 50

skip_commits:
  files:
      - default/
      - '**/*.md'
      - '**/*.xml'
      - '**/COPYING'
  message: /.*\[(skip appveyor)|(appveyor skip)\].*/

install:
  - cd ..
  - ps: Start-FileDownload https://github.com/freeorion/freeorion-sdk/releases/download/v10/FreeOrionSDK_10_MSVC-v140-xp.zip -FileName FreeOrionSDK.zip
  - unzip -q FreeOrionSDK.zip
  - cp bin/* freeorion/
  - cd freeorion

before_build:
  - cd msvc2017

build_script:
    - msbuild FreeOrion.sln /maxcpucount /property:BuildInParallel=true /property:CL_MPCount=2 /property:PlatformToolset=v140_xp /property:Configuration=Release-XP /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal

test: off
